version: '3.3'
services:
    mario:
        ports:
            - '8600:8080'
        image: ic-webapp/dockreg95
        container_name: mario
        networks:
            - games

    tetris:
        container_name: tetris
        ports:
            - '8888:80'
        restart: always
        image: ic-webapp/dockreg95
        networks:
            - games
networks:
    games:
        driver: bridge
        ipam:
          config:
            - subnet: 10.92.6.143/16